/**
 * Seeder: Demo Users
 * 
 * This seeder creates sample users for testing and development.
 * 5 samples for each user type: player, coach, club, partner, state, admin, super_admin
 * 
 * @author Pickleball Federation Team
 * @version 1.0.0
 */

'use strict';

const bcrypt = require('bcryptjs');

module.exports = {
  async up(queryInterface, Sequelize) {
    const hashedPassword = await bcrypt.hash('aaa', 10);
    const now = new Date();

    const users = [
      // Super Admin (1) - TOP PRIORITY
      {
        id: '550e8400-e29b-41d4-a716-446655440001',
        username: 'superadmin',
        email: 'admin@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Super Administrator',
        date_of_birth: '1980-01-15',
        gender: 'male',
        phone: '+52-55-1234-5678',
        profile_photo: 'https://example.com/photos/admin.jpg',
        bio: 'System administrator for Pickleball Federation',
        user_type: 'super_admin',
        skill_level: '5.0',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Vallarta 1234, Guadalajara, Jalisco',
        latitude: '20.65970000',
        longitude: '-103.34960000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'SUPA800115HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ admin_certificate: 'ADMIN123456' }),
        notes: 'System administrator with full access',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ admin_level: 'super', permissions: ['all'] }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Players (5)
      {
        id: '550e8400-e29b-41d4-a716-446655440002',
        username: 'john_player',
        email: 'john@email.com',
        password_hash: hashedPassword,
        full_name: 'John Smith',
        date_of_birth: '1990-03-15',
        gender: 'male',
        phone: '+52-55-6789-0123',
        profile_photo: 'https://example.com/photos/john.jpg',
        bio: 'Intermediate player looking for regular matches',
        user_type: 'player',
        skill_level: '3.5',
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Calle Libertad 123, Guadalajara, Jalisco',
        latitude: '20.65970000',
        longitude: '-103.34960000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'JONS900315HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ player_id: 'PLAYER123456' }),
        notes: 'Active intermediate player',
        preferences: JSON.stringify({ notifications: true, language: 'en' }),
        metadata: JSON.stringify({ player_stats: { matches_played: 45, tournaments_won: 2 } }),
        club_id: '660e8400-e29b-41d4-a716-446655440001',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440003',
        username: 'maria_player',
        email: 'maria@email.com',
        password_hash: hashedPassword,
        full_name: 'María González',
        date_of_birth: '1988-07-22',
        gender: 'female',
        phone: '+52-55-9876-5432',
        profile_photo: 'https://example.com/photos/maria.jpg',
        bio: 'Advanced player with competitive experience',
        user_type: 'player',
        skill_level: '4.5',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 456, Monterrey, Nuevo León',
        latitude: '25.68660000',
        longitude: '-100.31610000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'GONM880722NLCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ player_id: 'PLAYER123457' }),
        notes: 'Advanced competitive player',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ player_stats: { matches_played: 120, tournaments_won: 8 } }),
        club_id: '660e8400-e29b-41d4-a716-446655440002',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440004',
        username: 'carlos_player',
        email: 'carlos@email.com',
        password_hash: hashedPassword,
        full_name: 'Carlos Rodríguez',
        date_of_birth: '1995-11-10',
        gender: 'male',
        phone: '+52-55-5555-1234',
        profile_photo: 'https://example.com/photos/carlos.jpg',
        bio: 'Beginner player learning the game',
        user_type: 'player',
        skill_level: '2.5',
        membership_status: 'free',
        membership_expires_at: null,
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Zapopan',
        address: 'Calle Hidalgo 789, Zapopan, Jalisco',
        latitude: '20.72360000',
        longitude: '-103.39530000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'ROCC951110HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ player_id: 'PLAYER123458' }),
        notes: 'New beginner player',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ player_stats: { matches_played: 5, tournaments_won: 0 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440005',
        username: 'ana_player',
        email: 'ana@email.com',
        password_hash: hashedPassword,
        full_name: 'Ana Martínez',
        date_of_birth: '1985-04-18',
        gender: 'female',
        phone: '+52-55-4444-5678',
        profile_photo: 'https://example.com/photos/ana.jpg',
        bio: 'Experienced player with coaching background',
        user_type: 'player',
        skill_level: '5.0',
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Tlaquepaque',
        address: 'Calle Independencia 321, Tlaquepaque, Jalisco',
        latitude: '20.64090000',
        longitude: '-103.31030000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'MARA850418HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ player_id: 'PLAYER123459' }),
        notes: 'Experienced player with coaching experience',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ player_stats: { matches_played: 200, tournaments_won: 15 } }),
        club_id: '660e8400-e29b-41d4-a716-446655440001',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440006',
        username: 'luis_player',
        email: 'luis@email.com',
        password_hash: hashedPassword,
        full_name: 'Luis Hernández',
        date_of_birth: '1992-09-25',
        gender: 'male',
        phone: '+52-55-3333-9876',
        profile_photo: 'https://example.com/photos/luis.jpg',
        bio: 'Intermediate player focused on doubles',
        user_type: 'player',
        skill_level: '4.0',
        membership_status: 'basic',
        membership_expires_at: '2025-07-30T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'San Pedro Garza García',
        address: 'Av. Vasconcelos 654, San Pedro Garza García, Nuevo León',
        latitude: '25.65700000',
        longitude: '-100.40270000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'HEHL920925NLCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ player_id: 'PLAYER123460' }),
        notes: 'Doubles specialist player',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ player_stats: { matches_played: 80, tournaments_won: 3 } }),
        club_id: '660e8400-e29b-41d4-a716-446655440002',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Coaches (5)
      {
        id: '550e8400-e29b-41d4-a716-446655440007',
        username: 'sarah_coach',
        email: 'sarah@pickleballcoach.com',
        password_hash: hashedPassword,
        full_name: 'Sarah Johnson',
        date_of_birth: '1985-07-22',
        gender: 'female',
        phone: '+52-55-9876-5432',
        profile_photo: 'https://example.com/photos/sarah.jpg',
        bio: 'Certified pickleball coach with 10+ years experience',
        user_type: 'coach',
        skill_level: '5.5',
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Calle Morelos 789, Guadalajara, Jalisco',
        latitude: '20.65970000',
        longitude: '-103.34960000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'JONS850722HJCMNR01',
        rfc: null,
        website: 'https://www.sarahpickleballcoach.com',
        verification_documents: JSON.stringify({ coaching_certificate: 'CERT123456' }),
        notes: 'Excellent coach for beginners and intermediate players',
        preferences: JSON.stringify({ notifications: true, language: 'en' }),
        metadata: JSON.stringify({ coach_stats: { students: 25, certifications: ['USAPA', 'IPTPA'] } }),
        club_id: '660e8400-e29b-41d4-a716-446655440001',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440008',
        username: 'miguel_coach',
        email: 'miguel@pickleballcoach.com',
        password_hash: hashedPassword,
        full_name: 'Miguel Ángel López',
        date_of_birth: '1978-12-05',
        gender: 'male',
        phone: '+52-55-8765-4321',
        profile_photo: 'https://example.com/photos/miguel.jpg',
        bio: 'Former professional player turned coach',
        user_type: 'coach',
        skill_level: '5.5',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Revolución 123, Monterrey, Nuevo León',
        latitude: '25.68660000',
        longitude: '-100.31610000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'LOPM781205NLCMNR01',
        rfc: null,
        website: 'https://www.miguelpickleball.com',
        verification_documents: JSON.stringify({ coaching_certificate: 'CERT123457' }),
        notes: 'Professional coach with tournament experience',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ coach_stats: { students: 40, certifications: ['USAPA', 'IPTPA', 'PPR'] } }),
        club_id: '660e8400-e29b-41d4-a716-446655440002',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440009',
        username: 'patricia_coach',
        email: 'patricia@pickleballcoach.com',
        password_hash: hashedPassword,
        full_name: 'Patricia Ramírez',
        date_of_birth: '1982-03-15',
        gender: 'female',
        phone: '+52-55-7654-3210',
        profile_photo: 'https://example.com/photos/patricia.jpg',
        bio: 'Specialized in beginner and youth coaching',
        user_type: 'coach',
        skill_level: '5.0',
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Zapopan',
        address: 'Calle Juárez 456, Zapopan, Jalisco',
        latitude: '20.72360000',
        longitude: '-103.39530000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'RAMP820315HJCMNR01',
        rfc: null,
        website: 'https://www.patriciapickleball.com',
        verification_documents: JSON.stringify({ coaching_certificate: 'CERT123458' }),
        notes: 'Youth and beginner specialist',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ coach_stats: { students: 30, certifications: ['USAPA', 'Youth_Specialist'] } }),
        club_id: '660e8400-e29b-41d4-a716-446655440001',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440010',
        username: 'roberto_coach',
        email: 'roberto@pickleballcoach.com',
        password_hash: hashedPassword,
        full_name: 'Roberto Silva',
        date_of_birth: '1975-08-30',
        gender: 'male',
        phone: '+52-55-6543-2109',
        profile_photo: 'https://example.com/photos/roberto.jpg',
        bio: 'Advanced technique and strategy coach',
        user_type: 'coach',
        skill_level: '5.5',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Tlaquepaque',
        address: 'Calle Hidalgo 789, Tlaquepaque, Jalisco',
        latitude: '20.64090000',
        longitude: '-103.31030000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'SILR750830HJCMNR01',
        rfc: null,
        website: 'https://www.robertopickleball.com',
        verification_documents: JSON.stringify({ coaching_certificate: 'CERT123459' }),
        notes: 'Advanced technique specialist',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ coach_stats: { students: 35, certifications: ['USAPA', 'IPTPA', 'Advanced_Technique'] } }),
        club_id: '660e8400-e29b-41d4-a716-446655440001',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440011',
        username: 'carmen_coach',
        email: 'carmen@pickleballcoach.com',
        password_hash: hashedPassword,
        full_name: 'Carmen Vega',
        date_of_birth: '1988-11-12',
        gender: 'female',
        phone: '+52-55-5432-1098',
        profile_photo: 'https://example.com/photos/carmen.jpg',
        bio: 'Fitness and pickleball conditioning coach',
        user_type: 'coach',
        skill_level: '4.5',
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'San Pedro Garza García',
        address: 'Av. Vasconcelos 321, San Pedro Garza García, Nuevo León',
        latitude: '25.65700000',
        longitude: '-100.40270000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'VEGC881112NLCMNR01',
        rfc: null,
        website: 'https://www.carmenpickleball.com',
        verification_documents: JSON.stringify({ coaching_certificate: 'CERT123460' }),
        notes: 'Fitness and conditioning specialist',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ coach_stats: { students: 20, certifications: ['USAPA', 'Fitness_Specialist'] } }),
        club_id: '660e8400-e29b-41d4-a716-446655440002',
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Clubs (5)
      {
        id: '550e8400-e29b-41d4-a716-446655440012',
        username: 'elite_club',
        email: 'info@elitepickleball.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-33-1234-5678',
        profile_photo: 'https://example.com/photos/elite_club.jpg',
        bio: 'Premium pickleball club with professional facilities',
        user_type: 'club',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Vallarta 1234, Guadalajara, Jalisco',
        latitude: '20.65970000',
        longitude: '-103.34960000',
        timezone: 'America/Mexico_City',
        business_name: 'Elite Pickleball Club',
        contact_person: 'Carlos Mendoza',
        job_title: 'Club Director',
        curp: null,
        rfc: 'ELI987654321',
        website: 'https://www.elitepickleball.com',
        verification_documents: JSON.stringify({ club_license: 'CLUB123456' }),
        notes: 'Premium club with 6 courts and pro shop',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ club_stats: { courts: 6, members: 150, tournaments_hosted: 12 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440013',
        username: 'monterrey_club',
        email: 'info@monterreypickleball.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-81-9876-5432',
        profile_photo: 'https://example.com/photos/monterrey_club.jpg',
        bio: 'Competitive pickleball club in Monterrey',
        user_type: 'club',
        skill_level: null,
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 567, Monterrey, Nuevo León',
        latitude: '25.68660000',
        longitude: '-100.31610000',
        timezone: 'America/Mexico_City',
        business_name: 'Monterrey Pickleball Club',
        contact_person: 'Roberto Martínez',
        job_title: 'Club Manager',
        curp: null,
        rfc: 'MON987654321',
        website: 'https://www.monterreypickleball.com',
        verification_documents: JSON.stringify({ club_license: 'CLUB123457' }),
        notes: 'Competitive club with 4 courts',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ club_stats: { courts: 4, members: 120, tournaments_hosted: 8 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440014',
        username: 'zapopan_club',
        email: 'info@zapopanpickleball.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-33-5555-1234',
        profile_photo: 'https://example.com/photos/zapopan_club.jpg',
        bio: 'Family-friendly pickleball club in Zapopan',
        user_type: 'club',
        skill_level: null,
        membership_status: 'basic',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Zapopan',
        address: 'Calle Hidalgo 789, Zapopan, Jalisco',
        latitude: '20.72360000',
        longitude: '-103.39530000',
        timezone: 'America/Mexico_City',
        business_name: 'Zapopan Pickleball Club',
        contact_person: 'Ana López',
        job_title: 'Club Coordinator',
        curp: null,
        rfc: 'ZAP987654321',
        website: 'https://www.zapopanpickleball.com',
        verification_documents: JSON.stringify({ club_license: 'CLUB123458' }),
        notes: 'Family-friendly club with 3 courts',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ club_stats: { courts: 3, members: 80, tournaments_hosted: 4 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440015',
        username: 'tlaquepaque_club',
        email: 'info@tlaquepaquepickleball.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-33-4444-5678',
        profile_photo: 'https://example.com/photos/tlaquepaque_club.jpg',
        bio: 'Community pickleball club in Tlaquepaque',
        user_type: 'club',
        skill_level: null,
        membership_status: 'basic',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Tlaquepaque',
        address: 'Calle Independencia 321, Tlaquepaque, Jalisco',
        latitude: '20.64090000',
        longitude: '-103.31030000',
        timezone: 'America/Mexico_City',
        business_name: 'Tlaquepaque Pickleball Club',
        contact_person: 'Luis Hernández',
        job_title: 'Club President',
        curp: null,
        rfc: 'TLA987654321',
        website: 'https://www.tlaquepaquepickleball.com',
        verification_documents: JSON.stringify({ club_license: 'CLUB123459' }),
        notes: 'Community club with 2 courts',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ club_stats: { courts: 2, members: 60, tournaments_hosted: 2 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440016',
        username: 'sanpedro_club',
        email: 'info@sanpedropickleball.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-81-3333-9876',
        profile_photo: 'https://example.com/photos/sanpedro_club.jpg',
        bio: 'Luxury pickleball club in San Pedro Garza García',
        user_type: 'club',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'San Pedro Garza García',
        address: 'Av. Vasconcelos 654, San Pedro Garza García, Nuevo León',
        latitude: '25.65700000',
        longitude: '-100.40270000',
        timezone: 'America/Mexico_City',
        business_name: 'San Pedro Pickleball Club',
        contact_person: 'Patricia Ramírez',
        job_title: 'Club Director',
        curp: null,
        rfc: 'SAN987654321',
        website: 'https://www.sanpedropickleball.com',
        verification_documents: JSON.stringify({ club_license: 'CLUB123460' }),
        notes: 'Luxury club with 5 courts and spa facilities',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ club_stats: { courts: 5, members: 200, tournaments_hosted: 15 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Partners (5)
      {
        id: '550e8400-e29b-41d4-a716-446655440017',
        username: 'hotel_resort',
        email: 'info@hotelresort.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-55-1111-2222',
        profile_photo: 'https://example.com/photos/hotel.jpg',
        bio: 'Luxury hotel with dedicated pickleball courts',
        user_type: 'partner',
        skill_level: null,
        membership_status: 'basic',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Puerto Vallarta',
        address: 'Boulevard Francisco Medina Ascencio 999, Puerto Vallarta, Jalisco',
        latitude: '20.65970000',
        longitude: '-105.23330000',
        timezone: 'America/Mexico_City',
        business_name: 'Hotel Resort & Pickleball Center',
        contact_person: 'Carlos Mendoza',
        job_title: 'Sports Director',
        curp: null,
        rfc: 'HOT987654321',
        website: 'https://www.hotelresort.com',
        verification_documents: JSON.stringify({ hotel_license: 'HOT123456' }),
        notes: 'Partner hotel with excellent facilities',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ partner_stats: { courts: 4, hotel_rating: 4.5 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440018',
        username: 'sports_center',
        email: 'info@sportscenter.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-55-2222-3333',
        profile_photo: 'https://example.com/photos/sports_center.jpg',
        bio: 'Multi-sport center with pickleball facilities',
        user_type: 'partner',
        skill_level: null,
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Revolución 456, Monterrey, Nuevo León',
        latitude: '25.68660000',
        longitude: '-100.31610000',
        timezone: 'America/Mexico_City',
        business_name: 'Monterrey Sports Center',
        contact_person: 'Roberto Silva',
        job_title: 'Facility Manager',
        curp: null,
        rfc: 'SPO987654321',
        website: 'https://www.sportscenter.com',
        verification_documents: JSON.stringify({ facility_license: 'SPO123456' }),
        notes: 'Multi-sport facility with 3 pickleball courts',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ partner_stats: { courts: 3, facility_rating: 4.2 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440019',
        username: 'private_court',
        email: 'info@privatecourt.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-55-3333-4444',
        profile_photo: 'https://example.com/photos/private_court.jpg',
        bio: 'Private pickleball court rentals',
        user_type: 'partner',
        skill_level: null,
        membership_status: 'basic',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Zapopan',
        address: 'Calle Juárez 123, Zapopan, Jalisco',
        latitude: '20.72360000',
        longitude: '-103.39530000',
        timezone: 'America/Mexico_City',
        business_name: 'Private Court Rentals',
        contact_person: 'Ana Martínez',
        job_title: 'Court Manager',
        curp: null,
        rfc: 'PRI987654321',
        website: 'https://www.privatecourt.com',
        verification_documents: JSON.stringify({ court_license: 'PRI123456' }),
        notes: 'Private court rental service',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ partner_stats: { courts: 2, rental_rating: 4.0 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440020',
        username: 'beach_club',
        email: 'info@beachclub.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-55-4444-5555',
        profile_photo: 'https://example.com/photos/beach_club.jpg',
        bio: 'Beachfront club with pickleball courts',
        user_type: 'partner',
        skill_level: null,
        membership_status: 'premium',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Puerto Vallarta',
        address: 'Playa Los Muertos 789, Puerto Vallarta, Jalisco',
        latitude: '20.65970000',
        longitude: '-105.23330000',
        timezone: 'America/Mexico_City',
        business_name: 'Beach Club & Pickleball',
        contact_person: 'Luis Vega',
        job_title: 'Club Director',
        curp: null,
        rfc: 'BEA987654321',
        website: 'https://www.beachclub.com',
        verification_documents: JSON.stringify({ club_license: 'BEA123456' }),
        notes: 'Beachfront club with 3 courts',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ partner_stats: { courts: 3, beach_rating: 4.8 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440021',
        username: 'country_club',
        email: 'info@countryclub.com',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-55-5555-6666',
        profile_photo: 'https://example.com/photos/country_club.jpg',
        bio: 'Exclusive country club with pickleball facilities',
        user_type: 'partner',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'San Pedro Garza García',
        address: 'Av. Vasconcelos 987, San Pedro Garza García, Nuevo León',
        latitude: '25.65700000',
        longitude: '-100.40270000',
        timezone: 'America/Mexico_City',
        business_name: 'Country Club & Pickleball',
        contact_person: 'Patricia López',
        job_title: 'Sports Director',
        curp: null,
        rfc: 'COU987654321',
        website: 'https://www.countryclub.com',
        verification_documents: JSON.stringify({ club_license: 'COU123456' }),
        notes: 'Exclusive country club with 4 courts',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ partner_stats: { courts: 4, club_rating: 4.9 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // States (5)
      {
        id: '550e8400-e29b-41d4-a716-446655440022',
        username: 'jalisco_state',
        email: 'jalisco@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-33-1234-5678',
        profile_photo: 'https://example.com/photos/jalisco.jpg',
        bio: 'Official state representative for Jalisco Pickleball Federation',
        user_type: 'state',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Juárez 1234, Guadalajara, Jalisco',
        latitude: '20.65970000',
        longitude: '-103.34960000',
        timezone: 'America/Mexico_City',
        business_name: 'Jalisco State Pickleball Federation',
        contact_person: 'María González',
        job_title: 'State Director',
        curp: null,
        rfc: 'JAL987654321',
        website: 'https://www.jalisco-pickleball.mx',
        verification_documents: JSON.stringify({ state_license: 'JAL123456', federation_certificate: 'FED789012' }),
        notes: 'Official state representative with authority to organize state-level tournaments',
        preferences: JSON.stringify({ notifications: true, language: 'es', state_notifications: true }),
        metadata: JSON.stringify({ state_stats: { clubs: 15, players: 1200, tournaments_organized: 8 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440023',
        username: 'nuevoleon_state',
        email: 'nuevoleon@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-81-9876-5432',
        profile_photo: 'https://example.com/photos/nuevoleon.jpg',
        bio: 'Official state representative for Nuevo León Pickleball Federation',
        user_type: 'state',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 567, Monterrey, Nuevo León',
        latitude: '25.68660000',
        longitude: '-100.31610000',
        timezone: 'America/Mexico_City',
        business_name: 'Nuevo León State Pickleball Federation',
        contact_person: 'Roberto Martínez',
        job_title: 'State Director',
        curp: null,
        rfc: 'NLE987654321',
        website: 'https://www.nuevoleon-pickleball.mx',
        verification_documents: JSON.stringify({ state_license: 'NLE123456', federation_certificate: 'FED789013' }),
        notes: 'Official state representative with authority to organize state-level tournaments',
        preferences: JSON.stringify({ notifications: true, language: 'es', state_notifications: true }),
        metadata: JSON.stringify({ state_stats: { clubs: 12, players: 950, tournaments_organized: 6 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440024',
        username: 'quintanaroo_state',
        email: 'quintanaroo@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-984-1234-5678',
        profile_photo: 'https://example.com/photos/quintanaroo.jpg',
        bio: 'Official state representative for Quintana Roo Pickleball Federation',
        user_type: 'state',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Quintana Roo',
        city: 'Cancún',
        address: 'Av. Tulum 123, Cancún, Quintana Roo',
        latitude: '21.17430000',
        longitude: '-86.84660000',
        timezone: 'America/Mexico_City',
        business_name: 'Quintana Roo State Pickleball Federation',
        contact_person: 'Carlos Vega',
        job_title: 'State Director',
        curp: null,
        rfc: 'QUI987654321',
        website: 'https://www.quintanaroo-pickleball.mx',
        verification_documents: JSON.stringify({ state_license: 'QUI123456', federation_certificate: 'FED789014' }),
        notes: 'Official state representative for tourist destination state',
        preferences: JSON.stringify({ notifications: true, language: 'es', state_notifications: true }),
        metadata: JSON.stringify({ state_stats: { clubs: 8, players: 600, tournaments_organized: 4 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440025',
        username: 'bajacalifornia_state',
        email: 'bajacalifornia@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-664-9876-5432',
        profile_photo: 'https://example.com/photos/bajacalifornia.jpg',
        bio: 'Official state representative for Baja California Pickleball Federation',
        user_type: 'state',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Av. Revolución 456, Tijuana, Baja California',
        latitude: '32.51490000',
        longitude: '-117.03820000',
        timezone: 'America/Tijuana',
        business_name: 'Baja California State Pickleball Federation',
        contact_person: 'Ana Silva',
        job_title: 'State Director',
        curp: null,
        rfc: 'BAJ987654321',
        website: 'https://www.bajacalifornia-pickleball.mx',
        verification_documents: JSON.stringify({ state_license: 'BAJ123456', federation_certificate: 'FED789015' }),
        notes: 'Official state representative for border state',
        preferences: JSON.stringify({ notifications: true, language: 'es', state_notifications: true }),
        metadata: JSON.stringify({ state_stats: { clubs: 10, players: 800, tournaments_organized: 5 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440026',
        username: 'yucatan_state',
        email: 'yucatan@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: null,
        date_of_birth: null,
        gender: null,
        phone: '+52-999-5555-1234',
        profile_photo: 'https://example.com/photos/yucatan.jpg',
        bio: 'Official state representative for Yucatán Pickleball Federation',
        user_type: 'state',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Yucatán',
        city: 'Mérida',
        address: 'Paseo de Montejo 789, Mérida, Yucatán',
        latitude: '20.96740000',
        longitude: '-89.59260000',
        timezone: 'America/Mexico_City',
        business_name: 'Yucatán State Pickleball Federation',
        contact_person: 'Luis Ramírez',
        job_title: 'State Director',
        curp: null,
        rfc: 'YUC987654321',
        website: 'https://www.yucatan-pickleball.mx',
        verification_documents: JSON.stringify({ state_license: 'YUC123456', federation_certificate: 'FED789016' }),
        notes: 'Official state representative for Mayan heritage state',
        preferences: JSON.stringify({ notifications: true, language: 'es', state_notifications: true }),
        metadata: JSON.stringify({ state_stats: { clubs: 6, players: 450, tournaments_organized: 3 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Admins (5)
      {
        id: '550e8400-e29b-41d4-a716-446655440027',
        username: 'admin1',
        email: 'admin1@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Administrator One',
        date_of_birth: '1985-06-15',
        gender: 'male',
        phone: '+52-55-1111-1111',
        profile_photo: 'https://example.com/photos/admin1.jpg',
        bio: 'System administrator for user management',
        user_type: 'admin',
        skill_level: '4.0',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Vallarta 1000, Guadalajara, Jalisco',
        latitude: '20.65970000',
        longitude: '-103.34960000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'ADM1850615HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ admin_certificate: 'ADMIN123457' }),
        notes: 'User management administrator',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ admin_level: 'user_management', permissions: ['users', 'notifications'] }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440028',
        username: 'admin2',
        email: 'admin2@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Administrator Two',
        date_of_birth: '1988-09-22',
        gender: 'female',
        phone: '+52-55-2222-2222',
        profile_photo: 'https://example.com/photos/admin2.jpg',
        bio: 'Tournament and event administrator',
        user_type: 'admin',
        skill_level: '3.5',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 200, Monterrey, Nuevo León',
        latitude: '25.68660000',
        longitude: '-100.31610000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'ADM2880922NLCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ admin_certificate: 'ADMIN123458' }),
        notes: 'Tournament management administrator',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ admin_level: 'tournament_management', permissions: ['tournaments', 'events'] }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440029',
        username: 'admin3',
        email: 'admin3@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Administrator Three',
        date_of_birth: '1982-03-10',
        gender: 'male',
        phone: '+52-55-3333-3333',
        profile_photo: 'https://example.com/photos/admin3.jpg',
        bio: 'Payment and financial administrator',
        user_type: 'admin',
        skill_level: '4.5',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Zapopan',
        address: 'Calle Hidalgo 300, Zapopan, Jalisco',
        latitude: '20.72360000',
        longitude: '-103.39530000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'ADM3820310HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ admin_certificate: 'ADMIN123459' }),
        notes: 'Financial management administrator',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ admin_level: 'financial_management', permissions: ['payments', 'reports'] }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440030',
        username: 'admin4',
        email: 'admin4@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Administrator Four',
        date_of_birth: '1990-12-05',
        gender: 'female',
        phone: '+52-55-4444-4444',
        profile_photo: 'https://example.com/photos/admin4.jpg',
        bio: 'Content and media administrator',
        user_type: 'admin',
        skill_level: '3.0',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Tlaquepaque',
        address: 'Calle Independencia 400, Tlaquepaque, Jalisco',
        latitude: '20.64090000',
        longitude: '-103.31030000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'ADM4901205HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ admin_certificate: 'ADMIN123460' }),
        notes: 'Content management administrator',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ admin_level: 'content_management', permissions: ['content', 'media'] }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },
      {
        id: '550e8400-e29b-41d4-a716-446655440031',
        username: 'admin5',
        email: 'admin5@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Administrator Five',
        date_of_birth: '1987-07-18',
        gender: 'male',
        phone: '+52-55-5555-5555',
        profile_photo: 'https://example.com/photos/admin5.jpg',
        bio: 'System and technical administrator',
        user_type: 'admin',
        skill_level: '4.0',
        membership_status: 'elite',
        membership_expires_at: '2025-12-31T23:59:59.000Z',
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'San Pedro Garza García',
        address: 'Av. Vasconcelos 500, San Pedro Garza García, Nuevo León',
        latitude: '25.65700000',
        longitude: '-100.40270000',
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'ADM5870718NLCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ admin_certificate: 'ADMIN123461' }),
        notes: 'Technical system administrator',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ admin_level: 'technical_admin', permissions: ['system', 'technical'] }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      }
    ];

    await queryInterface.bulkInsert('users', users, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('users', null, {});
  }
}; 