/**
 * Seeder: Demo Users
 * 
 * This seeder creates sample users for testing and development.
 * Includes players, coaches, club owners, admins, and partners.
 * 
 * @author Pickleball Federation Team
 * @version 1.0.0
 */

'use strict';

const bcrypt = require('bcryptjs');

module.exports = {
  async up(queryInterface, Sequelize) {
    const hashedPassword = await bcrypt.hash('password123', 10);
    const now = new Date();

    const users = [
      // Super Admin
      {
        id: '550e8400-e29b-41d4-a716-446655440001',
        username: 'superadmin',
        email: 'admin@pickleballfederation.mx',
        password_hash: hashedPassword,
        first_name: 'Super',
        last_name: 'Administrator',
        full_name: 'Super Administrator',
        date_of_birth: '1980-01-15',
        gender: 'male',
        phone: '+52-55-1234-5678',
        profile_photo: 'https://example.com/photos/admin.jpg',
        bio: 'System administrator for Pickleball Federation',
        user_type: 'super_admin',
        role: 'super_admin',
        skill_level: '5.0',
        membership_status: 'elite',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Vallarta 1234, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      // Admin Users
      {
        id: '550e8400-e29b-41d4-a716-446655440002',
        username: 'admin1',
        email: 'admin1@pickleballfederation.mx',
        password_hash: hashedPassword,
        first_name: 'María',
        last_name: 'González',
        full_name: 'María González',
        date_of_birth: '1985-03-20',
        gender: 'female',
        phone: '+52-55-2345-6789',
        profile_photo: 'https://example.com/photos/maria.jpg',
        bio: 'Administrator for tournament management',
        user_type: 'admin',
        role: 'admin',
        skill_level: '4.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 567, Monterrey, NL',
        latitude: 25.6866,
        longitude: -100.3161,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440003',
        username: 'admin2',
        email: 'admin2@pickleballfederation.mx',
        password_hash: hashedPassword,
        first_name: 'Carlos',
        last_name: 'Rodríguez',
        full_name: 'Carlos Rodríguez',
        date_of_birth: '1982-07-10',
        gender: 'male',
        phone: '+52-55-3456-7890',
        profile_photo: 'https://example.com/photos/carlos.jpg',
        bio: 'Administrator for club management',
        user_type: 'admin',
        role: 'admin',
        skill_level: '4.0',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Blvd. Agua Caliente 890, Tijuana, BC',
        latitude: 32.5149,
        longitude: -117.0382,
        timezone: 'America/Tijuana',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      // Club Owners
      {
        id: '550e8400-e29b-41d4-a716-446655440004',
        username: 'clubowner1',
        email: 'owner@pickleballguadalajara.mx',
        password_hash: hashedPassword,
        first_name: 'Ana',
        last_name: 'Martínez',
        full_name: 'Ana Martínez',
        date_of_birth: '1978-11-05',
        gender: 'female',
        phone: '+52-33-4567-8901',
        profile_photo: 'https://example.com/photos/ana.jpg',
        bio: 'Owner of Pickleball Guadalajara Club',
        user_type: 'club',
        role: 'user',
        skill_level: '4.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Chapultepec 123, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440005',
        username: 'clubowner2',
        email: 'owner@pickleballmonterrey.mx',
        password_hash: hashedPassword,
        first_name: 'Roberto',
        last_name: 'Hernández',
        full_name: 'Roberto Hernández',
        date_of_birth: '1980-04-15',
        gender: 'male',
        phone: '+52-81-5678-9012',
        profile_photo: 'https://example.com/photos/roberto.jpg',
        bio: 'Owner of Pickleball Monterrey Club',
        user_type: 'club',
        role: 'user',
        skill_level: '4.0',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. San Pedro 456, Monterrey, NL',
        latitude: 25.6866,
        longitude: -100.3161,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440006',
        username: 'clubowner3',
        email: 'owner@pickleballtijuana.mx',
        password_hash: hashedPassword,
        first_name: 'Patricia',
        last_name: 'López',
        full_name: 'Patricia López',
        date_of_birth: '1983-09-22',
        gender: 'female',
        phone: '+52-664-6789-0123',
        profile_photo: 'https://example.com/photos/patricia.jpg',
        bio: 'Owner of Pickleball Tijuana Club',
        user_type: 'club',
        role: 'user',
        skill_level: '4.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Blvd. Díaz Ordaz 789, Tijuana, BC',
        latitude: 32.5149,
        longitude: -117.0382,
        timezone: 'America/Tijuana',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      // Coaches
      {
        id: '550e8400-e29b-41d4-a716-446655440007',
        username: 'coach1',
        email: 'coach1@pickleballfederation.mx',
        password_hash: hashedPassword,
        first_name: 'Miguel',
        last_name: 'Sánchez',
        full_name: 'Miguel Sánchez',
        date_of_birth: '1985-06-12',
        gender: 'male',
        phone: '+52-33-7890-1234',
        profile_photo: 'https://example.com/photos/miguel.jpg',
        bio: 'Certified Pickleball Coach - Level 2',
        user_type: 'coach',
        role: 'user',
        skill_level: '5.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. México 321, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440008',
        username: 'coach2',
        email: 'coach2@pickleballfederation.mx',
        password_hash: hashedPassword,
        first_name: 'Sofia',
        last_name: 'Ramírez',
        full_name: 'Sofia Ramírez',
        date_of_birth: '1988-02-28',
        gender: 'female',
        phone: '+52-81-8901-2345',
        profile_photo: 'https://example.com/photos/sofia.jpg',
        bio: 'Certified Pickleball Coach - Level 1',
        user_type: 'coach',
        role: 'user',
        skill_level: '5.0',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Universidad 654, Monterrey, NL',
        latitude: 25.6866,
        longitude: -100.3161,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440009',
        username: 'coach3',
        email: 'coach3@pickleballfederation.mx',
        password_hash: hashedPassword,
        first_name: 'Diego',
        last_name: 'Morales',
        full_name: 'Diego Morales',
        date_of_birth: '1987-12-03',
        gender: 'male',
        phone: '+52-664-9012-3456',
        profile_photo: 'https://example.com/photos/diego.jpg',
        bio: 'Certified Pickleball Coach - Level 2',
        user_type: 'coach',
        role: 'user',
        skill_level: '5.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Blvd. Cucapah 987, Tijuana, BC',
        latitude: 32.5149,
        longitude: -117.0382,
        timezone: 'America/Tijuana',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      // Players - Guadalajara
      {
        id: '550e8400-e29b-41d4-a716-446655440010',
        username: 'player1',
        email: 'player1@example.com',
        password_hash: hashedPassword,
        first_name: 'Juan',
        last_name: 'Pérez',
        full_name: 'Juan Pérez',
        date_of_birth: '1990-05-18',
        gender: 'male',
        phone: '+52-33-0123-4567',
        profile_photo: 'https://example.com/photos/juan.jpg',
        bio: 'Passionate pickleball player from Guadalajara',
        user_type: 'player',
        role: 'user',
        skill_level: '4.0',
        membership_status: 'basic',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Calle Libertad 123, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440011',
        username: 'player2',
        email: 'player2@example.com',
        password_hash: hashedPassword,
        first_name: 'Carmen',
        last_name: 'García',
        full_name: 'Carmen García',
        date_of_birth: '1992-08-25',
        gender: 'female',
        phone: '+52-33-1234-5678',
        profile_photo: 'https://example.com/photos/carmen.jpg',
        bio: 'Competitive player looking for doubles partners',
        user_type: 'player',
        role: 'user',
        skill_level: '4.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Hidalgo 456, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440012',
        username: 'player3',
        email: 'player3@example.com',
        password_hash: hashedPassword,
        first_name: 'Luis',
        last_name: 'Fernández',
        full_name: 'Luis Fernández',
        date_of_birth: '1988-03-14',
        gender: 'male',
        phone: '+52-33-2345-6789',
        profile_photo: 'https://example.com/photos/luis.jpg',
        bio: 'Recreational player enjoying the sport',
        user_type: 'player',
        role: 'user',
        skill_level: '3.5',
        membership_status: 'free',
        membership_expires_at: null,
        email_verified: true,
        is_active: true,
        is_verified: false,
        last_login: now,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Calle Morelos 789, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        preferences: { notifications: false, language: 'es' },
        created_at: now,
        updated_at: now
      },

      // Players - Monterrey
      {
        id: '550e8400-e29b-41d4-a716-446655440013',
        username: 'player4',
        email: 'player4@example.com',
        password_hash: hashedPassword,
        first_name: 'Alejandra',
        last_name: 'Torres',
        full_name: 'Alejandra Torres',
        date_of_birth: '1991-11-07',
        gender: 'female',
        phone: '+52-81-3456-7890',
        profile_photo: 'https://example.com/photos/alejandra.jpg',
        bio: 'Tournament player from Monterrey',
        user_type: 'player',
        role: 'user',
        skill_level: '4.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Garza Sada 321, Monterrey, NL',
        latitude: 25.6866,
        longitude: -100.3161,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440014',
        username: 'player5',
        email: 'player5@example.com',
        password_hash: hashedPassword,
        first_name: 'Ricardo',
        last_name: 'Vargas',
        full_name: 'Ricardo Vargas',
        date_of_birth: '1989-07-30',
        gender: 'male',
        phone: '+52-81-4567-8901',
        profile_photo: 'https://example.com/photos/ricardo.jpg',
        bio: 'Doubles specialist looking for tournaments',
        user_type: 'player',
        role: 'user',
        skill_level: '4.0',
        membership_status: 'basic',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Lázaro Cárdenas 654, Monterrey, NL',
        latitude: 25.6866,
        longitude: -100.3161,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440015',
        username: 'player6',
        email: 'player6@example.com',
        password_hash: hashedPassword,
        first_name: 'Mariana',
        last_name: 'Cruz',
        full_name: 'Mariana Cruz',
        date_of_birth: '1993-04-12',
        gender: 'female',
        phone: '+52-81-5678-9012',
        profile_photo: 'https://example.com/photos/mariana.jpg',
        bio: 'Beginner player learning the game',
        user_type: 'player',
        role: 'user',
        skill_level: '2.5',
        membership_status: 'free',
        membership_expires_at: null,
        email_verified: true,
        is_active: true,
        is_verified: false,
        last_login: now,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 987, Monterrey, NL',
        latitude: 25.6866,
        longitude: -100.3161,
        timezone: 'America/Mexico_City',
        preferences: { notifications: false, language: 'es' },
        created_at: now,
        updated_at: now
      },

      // Players - Tijuana
      {
        id: '550e8400-e29b-41d4-a716-446655440016',
        username: 'player7',
        email: 'player7@example.com',
        password_hash: hashedPassword,
        first_name: 'Fernando',
        last_name: 'Jiménez',
        full_name: 'Fernando Jiménez',
        date_of_birth: '1986-09-18',
        gender: 'male',
        phone: '+52-664-6789-0123',
        profile_photo: 'https://example.com/photos/fernando.jpg',
        bio: 'Competitive player from Tijuana',
        user_type: 'player',
        role: 'user',
        skill_level: '4.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Blvd. Salinas 123, Tijuana, BC',
        latitude: 32.5149,
        longitude: -117.0382,
        timezone: 'America/Tijuana',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440017',
        username: 'player8',
        email: 'player8@example.com',
        password_hash: hashedPassword,
        first_name: 'Valeria',
        last_name: 'Ruiz',
        full_name: 'Valeria Ruiz',
        date_of_birth: '1990-12-05',
        gender: 'female',
        phone: '+52-664-7890-1234',
        profile_photo: 'https://example.com/photos/valeria.jpg',
        bio: 'Singles player looking for practice partners',
        user_type: 'player',
        role: 'user',
        skill_level: '4.0',
        membership_status: 'basic',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Blvd. Insurgentes 456, Tijuana, BC',
        latitude: 32.5149,
        longitude: -117.0382,
        timezone: 'America/Tijuana',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440018',
        username: 'player9',
        email: 'player9@example.com',
        password_hash: hashedPassword,
        first_name: 'Oscar',
        last_name: 'Mendoza',
        full_name: 'Oscar Mendoza',
        date_of_birth: '1994-01-28',
        gender: 'male',
        phone: '+52-664-8901-2345',
        profile_photo: 'https://example.com/photos/oscar.jpg',
        bio: 'New player excited to learn',
        user_type: 'player',
        role: 'user',
        skill_level: '3.0',
        membership_status: 'free',
        membership_expires_at: null,
        email_verified: true,
        is_active: true,
        is_verified: false,
        last_login: now,
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Blvd. 2000 789, Tijuana, BC',
        latitude: 32.5149,
        longitude: -117.0382,
        timezone: 'America/Tijuana',
        preferences: { notifications: false, language: 'es' },
        created_at: now,
        updated_at: now
      },

      // Partners
      {
        id: '550e8400-e29b-41d4-a716-446655440019',
        username: 'partner1',
        email: 'partner@equipmentmx.com',
        password_hash: hashedPassword,
        first_name: 'Roberto',
        last_name: 'Silva',
        full_name: 'Roberto Silva',
        date_of_birth: '1975-06-15',
        gender: 'male',
        phone: '+52-55-9012-3456',
        profile_photo: 'https://example.com/photos/roberto_silva.jpg',
        bio: 'Equipment supplier for Pickleball Federation',
        user_type: 'partner',
        role: 'user',
        skill_level: '3.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Ciudad de México',
        city: 'Ciudad de México',
        address: 'Av. Insurgentes Sur 1234, CDMX',
        latitude: 19.4326,
        longitude: -99.1332,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      },

      {
        id: '550e8400-e29b-41d4-a716-446655440020',
        username: 'partner2',
        email: 'partner@sponsorsmx.com',
        password_hash: hashedPassword,
        first_name: 'Isabella',
        last_name: 'Castro',
        full_name: 'Isabella Castro',
        date_of_birth: '1980-03-22',
        gender: 'female',
        phone: '+52-55-0123-4567',
        profile_photo: 'https://example.com/photos/isabella.jpg',
        bio: 'Sponsorship coordinator for tournaments',
        user_type: 'partner',
        role: 'user',
        skill_level: '3.0',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        is_active: true,
        is_verified: true,
        last_login: now,
        state: 'Ciudad de México',
        city: 'Ciudad de México',
        address: 'Av. Reforma 567, CDMX',
        latitude: 19.4326,
        longitude: -99.1332,
        timezone: 'America/Mexico_City',
        preferences: { notifications: true, language: 'es' },
        created_at: now,
        updated_at: now
      }
    ];

    await queryInterface.bulkInsert('users', users, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('users', null, {});
  }
}; 