/**
 * User Seeder
 * 
 * Seeds the database with initial users for the Pickleball Federation system.
 * Creates 1 admin and 5 users of each other type (player, coach, club, partner, state).
 * 
 * @author Pickleball Federation Team  
 * @version 1.0.0
 */
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
module.exports = {
  up: async (queryInterface, Sequelize) => {
    const saltRounds = 12;
    const hashedPassword = await bcrypt.hash('aaa!', saltRounds);
    const users = [
      // 1 Admin User
      {
        id: uuidv4(),
        username: 'admin_super',
        email: 'admin@pickleballfederacion.mx',
        password_hash: hashedPassword,
        user_type: 'admin',
        full_name: 'Administrador Principal',
        phone: '+52-55-1234-5678',
        state: 'CDMX',
        city: 'Ciudad de México',
        address: 'Av. Reforma 123, Col. Centro',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      // 5 Player Users
      {
        id: uuidv4(),
        username: 'maria_gonzalez',
        email: 'maria.gonzalez@email.com',
        password_hash: hashedPassword,
        user_type: 'player',
        full_name: 'María González Rodríguez',
        date_of_birth: new Date('1985-03-15'),
        gender: 'female',
        phone: '+52-33-2345-6789',
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Calle Juárez 456, Col. Centro',
        skill_level: '4.0',
        curp: 'GORM850315MJCLRD01',
        membership_status: 'basic',
        can_be_found: true,
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'carlos_martinez',
        email: 'carlos.martinez@email.com',
        password_hash: hashedPassword,
        user_type: 'player',
        full_name: 'Carlos Martínez López',
        date_of_birth: new Date('1990-07-22'),
        gender: 'male',
        phone: '+52-81-3456-7890',
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Universidad 789, Col. San Nicolás',
        skill_level: '3.5',
        curp: 'MALC900722HNLRPR02',
        membership_status: 'basic',
        can_be_found: true,
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'ana_rodriguez',
        email: 'ana.rodriguez@email.com',
        password_hash: hashedPassword,
        user_type: 'player',
        full_name: 'Ana Rodríguez Hernández',
        date_of_birth: new Date('1988-12-10'),
        gender: 'female',
        phone: '+52-998-4567-8901',
        state: 'Quintana Roo',
        city: 'Cancún',
        address: 'Av. Tulum 321, SM 22',
        skill_level: '4.5',
        curp: 'ROHA881210MQTDRN03',
        membership_status: 'basic',
        can_be_found: true,
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'luis_hernandez',
        email: 'luis.hernandez@email.com',
        password_hash: hashedPassword,
        user_type: 'player',
        full_name: 'Luis Hernández García',
        date_of_birth: new Date('1992-05-18'),
        gender: 'male',
        phone: '+52-222-5678-9012',
        state: 'Puebla',
        city: 'Puebla',
        address: 'Calle 5 de Mayo 654, Centro Histórico',
        skill_level: '3.0',
        curp: 'HEGL920518HPLRRS04',
        membership_status: 'free',
        membership_status: 'basic',
        can_be_found: true,
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'sofia_lopez',
        email: 'sofia.lopez@email.com',
        password_hash: hashedPassword,
        user_type: 'player',
        full_name: 'Sofía López Martínez',
        date_of_birth: new Date('1987-09-25'),
        gender: 'female',
        phone: '+52-442-6789-0123',
        state: 'Querétaro',
        city: 'Querétaro',
        address: 'Blvd. Bernardo Quintana 987, Col. San Pablo',
        skill_level: '5.0',
        curp: 'LOMS870925MQTPRF05',
        membership_status: 'elite',
        membership_status: 'basic',
        can_be_found: true,
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      // 5 Coach Users  
      {
        id: uuidv4(),
        username: 'coach_ramirez',
        email: 'entrenador.ramirez@email.com',
        password_hash: hashedPassword,
        user_type: 'coach',
        full_name: 'Roberto Ramírez Sánchez',
        date_of_birth: new Date('1975-11-08'),
        gender: 'male',
        phone: '+52-33-7890-1234',
        state: 'Jalisco',
        city: 'Zapopan',
        address: 'Av. López Mateos 1234, Col. Providencia',
        skill_level: '5.0',
        curp: 'RASR751108HJCMNT06',
        coaching_experience: 15,
        specializations: JSON.stringify(['serve', 'volley', 'strategy', 'doubles']),
        hourly_rate: 500.00,
        available_for_lessons: true,
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'coach_morales',
        email: 'patricia.morales@email.com',
        password_hash: hashedPassword,
        user_type: 'coach',
        full_name: 'Patricia Morales Jiménez',
        date_of_birth: new Date('1980-04-12'),
        gender: 'female',
        phone: '+52-55-8901-2345',
        state: 'Estado de México',
        city: 'Toluca',
        address: 'Calle Morelos 567, Col. Centro',
        skill_level: '4.5',
        curp: 'MOJP800412MMCRMT07',
        coaching_experience: 10,
        specializations: JSON.stringify(['beginners', 'fundamentals']),
        hourly_rate: 450.00,
        available_for_lessons: true,
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'coach_vargas',
        email: 'diego.vargas@email.com',
        password_hash: hashedPassword,
        user_type: 'coach',
        full_name: 'Diego Vargas Ruiz',
        date_of_birth: new Date('1983-08-30'),
        gender: 'male',
        phone: '+52-81-9012-3456',
        state: 'Nuevo León',
        city: 'San Pedro Garza García',
        address: 'Av. Vasconcelos 890, Col. Del Valle',
        skill_level: '5.0',
        curp: 'VARD830830HNLRGR08',
        coaching_experience: 12,
        specializations: JSON.stringify(['advanced', 'tournament_prep']),
        hourly_rate: 600.00,
        available_for_lessons: true,
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'coach_torres',
        email: 'elena.torres@email.com',
        password_hash: hashedPassword,
        user_type: 'coach',
        full_name: 'Elena Torres Vázquez',
        date_of_birth: new Date('1978-01-17'),
        gender: 'female',
        phone: '+52-664-0123-4567',
        state: 'Baja California',
        city: 'Tijuana',
        address: 'Blvd. Agua Caliente 2345, Zona Río',
        skill_level: '4.5',
        curp: 'TOVE780117MBCRLN09',
        coaching_experience: 8,
        specializations: JSON.stringify(['youth', 'women']),
        hourly_rate: 400.00,
        available_for_lessons: true,
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'coach_gutierrez',
        email: 'fernando.gutierrez@email.com',
        password_hash: hashedPassword,
        user_type: 'coach',
        full_name: 'Fernando Gutiérrez Mendoza',
        date_of_birth: new Date('1982-06-03'),
        gender: 'male',
        phone: '+52-228-1234-5678',
        state: 'Veracruz',
        city: 'Xalapa',
        address: 'Av. Ávila Camacho 678, Col. Centro',
        skill_level: '5.0',
        curp: 'GUMF820603HVZTNR10',
        membership_status: 'elite',
        coaching_experience: 18,
        specializations: JSON.stringify(['professional', 'biomechanics']),
        hourly_rate: 550.00,
        available_for_lessons: true,
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      // 5 Club Users
      {
        id: uuidv4(),
        username: 'elite_pickleball',
        email: 'admin@elitepickleball.mx',
        password_hash: hashedPassword,
        user_type: 'club',
        business_name: 'Elite Pickleball Club Guadalajara',
        contact_person: 'Alejandro Ruiz Moreno',
        full_name: 'Elite Pickleball Club Guadalajara',
        phone: '+52-33-2468-1357',
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Patria 3456, Col. Jardines del Bosque',
        website: 'https://www.elitepickleball.mx',
        rfc: 'EPC240101ABC',
        membership_status: 'premium',
        job_title: 'Director General',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'metro_sports',
        email: 'contacto@metrosports.mx',
        password_hash: hashedPassword,
        user_type: 'club',
        business_name: 'Metro Sports Center CDMX',
        contact_person: 'Gabriela Mendoza Silva',
        full_name: 'Metro Sports Center CDMX',
        phone: '+52-55-3579-2468',
        state: 'CDMX',
        city: 'Ciudad de México',
        address: 'Av. Insurgentes Sur 4567, Col. Del Valle',
        website: 'https://www.metrosports.mx',
        rfc: 'MSC240102DEF',
        membership_status: 'premium',
        job_title: 'Gerente de Operaciones',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'regio_club',
        email: 'info@regioclub.mx',
        password_hash: hashedPassword,
        user_type: 'club',
        business_name: 'Regio Pickleball Club',
        contact_person: 'Ricardo Salinas Vega',
        full_name: 'Regio Pickleball Club',
        phone: '+52-81-4680-3579',
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 5678, Col. Centro',
        website: 'https://www.regioclub.mx',
        rfc: 'RPC240103GHI',
        membership_status: 'premium',
        job_title: 'Director Deportivo',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'playa_courts',
        email: 'administracion@playacourts.mx',
        password_hash: hashedPassword,
        user_type: 'club',
        business_name: 'Playa Courts Cancún',
        contact_person: 'Marina López Castillo',
        full_name: 'Playa Courts Cancún',
        phone: '+52-998-5791-4680',
        state: 'Quintana Roo',
        city: 'Cancún',
        address: 'Blvd. Kukulcán Km 15, Zona Hotelera',
        website: 'https://www.playacourts.mx',
        rfc: 'PCC240104JKL',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'bajio_pickleball',
        email: 'contacto@bajiopickleball.mx',
        password_hash: hashedPassword,
        user_type: 'club',
        business_name: 'Bajío Pickleball Academy',
        contact_person: 'Héctor Jiménez Ramos',
        full_name: 'Bajío Pickleball Academy',
        phone: '+52-442-6802-5791',
        state: 'Querétaro',
        city: 'Querétaro',
        address: 'Carretera a Celaya 6789, Col. Juriquilla',
        website: 'https://www.bajiopickleball.mx',
        rfc: 'BPA240105MNO',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      // 5 Partner Users
      {
        id: uuidv4(),
        username: 'deportex_mx',
        email: 'ventas@deportex.mx',
        password_hash: hashedPassword,
        user_type: 'partner',
        business_name: 'DeporTex México',
        contact_person: 'Raúl Fernández Torres',
        full_name: 'DeporTex México',
        phone: '+52-33-7913-5802',
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Parque Industrial El Álamo, Nave 15',
        website: 'https://www.deportex.mx',
        rfc: 'DTM240106PQR',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'equipment_pro',
        email: 'info@equipmentpro.mx',
        password_hash: hashedPassword,
        user_type: 'partner',
        business_name: 'Equipment Pro Sports',
        contact_person: 'Silvia Herrera Campos',
        full_name: 'Equipment Pro Sports',
        phone: '+52-55-8024-6913',
        state: 'CDMX',
        city: 'Ciudad de México',
        address: 'Eje Central Lázaro Cárdenas 890, Col. Centro',
        website: 'https://www.equipmentpro.mx',
        rfc: 'EPS240107STU',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'norte_sports',
        email: 'contacto@nortesports.mx',
        password_hash: hashedPassword,
        user_type: 'partner',
        business_name: 'Norte Sports Distribution',
        contact_person: 'Miguel Ángel Rojas Vega',
        full_name: 'Norte Sports Distribution',
        phone: '+52-81-9135-8024',
        state: 'Nuevo León',
        city: 'Apodaca',
        address: 'Parque Industrial Finsa, Bodega 23',
        website: 'https://www.nortesports.mx',
        rfc: 'NSD240108VWX',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'caribe_gear',
        email: 'ventas@caribegear.mx',
        password_hash: hashedPassword,
        user_type: 'partner',
        business_name: 'Caribe Gear & Equipment',
        contact_person: 'Lorena Castillo Morales',
        full_name: 'Caribe Gear & Equipment',
        phone: '+52-998-0246-9135',
        state: 'Quintana Roo',
        city: 'Playa del Carmen',
        address: 'Av. Constituyentes 1234, Col. Ejidal',
        website: 'https://www.caribegear.mx',
        rfc: 'CGE240109YZA',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'central_supplies',
        email: 'admin@centralsupplies.mx',
        password_hash: hashedPassword,
        user_type: 'partner',
        business_name: 'Central Supplies México',
        contact_person: 'Arturo Mendoza Ruiz',
        full_name: 'Central Supplies México',
        phone: '+52-442-1357-0246',
        state: 'Querétaro',
        city: 'San Juan del Río',
        address: 'Zona Industrial San Juan, Lote 45',
        website: 'https://www.centralsupplies.mx',
        rfc: 'CSM240110BCD',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      // 5 State Users
      {
        id: uuidv4(),
        username: 'jalisco_fed',
        email: 'presidencia@jaliscopickleball.mx',
        password_hash: hashedPassword,
        user_type: 'state',
        business_name: 'Federación de Pickleball de Jalisco',
        contact_person: 'Ing. Carmen Elizondo Vázquez',
        full_name: 'Federación de Pickleball de Jalisco',
        phone: '+52-33-2580-1470',
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Américas 2580, Col. Providencia',
        website: 'https://www.jaliscopickleball.mx',
        rfc: 'FPJ240111EFG',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'cdmx_fed',
        email: 'direccion@cdmxpickleball.mx',
        password_hash: hashedPassword,
        user_type: 'state',
        business_name: 'Asociación de Pickleball CDMX',
        contact_person: 'Lic. Eduardo Morales Jiménez',
        full_name: 'Asociación de Pickleball CDMX',
        phone: '+52-55-3691-2580',
        state: 'CDMX',
        city: 'Ciudad de México',
        address: 'Paseo de la Reforma 3691, Col. Polanco',
        website: 'https://www.cdmxpickleball.mx',
        rfc: 'APC240112HIJ',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'nl_fed',
        email: 'secretaria@nuevoleonpickleball.mx',
        password_hash: hashedPassword,
        user_type: 'state',
        business_name: 'Comité Estatal de Pickleball Nuevo León',
        contact_person: 'Mtro. Javier Salinas Rodríguez',
        full_name: 'Comité Estatal de Pickleball Nuevo León',
        phone: '+52-81-4702-3691',
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Garza Sada 4702, Col. Tecnológico',
        website: 'https://www.nuevoleonpickleball.mx',
        rfc: 'CEP240113KLM',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'qr_fed',
        email: 'coordinacion@qrpickleball.mx',
        password_hash: hashedPassword,
        user_type: 'state',
        business_name: 'Federación de Pickleball Quintana Roo',
        contact_person: 'Dra. Isabel Vargas Herrera',
        full_name: 'Federación de Pickleball Quintana Roo',
        phone: '+52-998-5813-4702',
        state: 'Quintana Roo',
        city: 'Cancún',
        address: 'Av. Bonampak 5813, SM 10',
        website: 'https://www.qrpickleball.mx',
        rfc: 'FPQ240114NOP',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish', 'English']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        username: 'qro_fed',
        email: 'presidencia@queretaropickleball.mx',
        password_hash: hashedPassword,
        user_type: 'state',
        business_name: 'Liga Queretana de Pickleball',
        contact_person: 'Arq. Roberto Torres Mendoza',
        full_name: 'Liga Queretana de Pickleball',
        phone: '+52-442-6924-5813',
        state: 'Querétaro',
        city: 'Querétaro',
        address: 'Blvd. Bernardo Quintana 6924, Col. Lomas de Querétaro',
        website: 'https://www.queretaropickleball.mx',
        rfc: 'LQP240115QRS',
        membership_status: 'premium',
        is_findable: true,
        coaching_languages: JSON.stringify(['Spanish']),
        is_active: true,
        is_verified: true,
        email_verified: true,
        created_at: new Date(),
        updated_at: new Date()
      }
    ];
    await queryInterface.bulkInsert('users', users, {});
    console.log('✅ Successfully seeded users: 1 admin, 5 players, 5 coaches, 5 clubs, 5 partners, 5 state federations');
  },
  down: async (queryInterface) => {
    await queryInterface.bulkDelete('users', null, {});
    console.log('🗑️ All seeded users have been removed');
  }
};