/**
 * Seeder: Demo Users
 * 
 * This seeder creates sample users for testing and development.
 * 
 * @author Pickleball Federation Team
 * @version 1.0.0
 */

'use strict';

const bcrypt = require('bcryptjs');

module.exports = {
  async up(queryInterface, Sequelize) {
    const hashedPassword = await bcrypt.hash('123', 10);
    const now = new Date();

    const users = [
      // Super Admin
      {
        id: '550e8400-e29b-41d4-a716-446655440001',
        username: 'superadmin',
        email: 'admin@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Super Administrator',
        date_of_birth: '1980-01-15',
        gender: 'male',
        phone: '+52-55-1234-5678',
        profile_photo: 'https://example.com/photos/admin.jpg',
        bio: 'System administrator for Pickleball Federation',
        user_type: 'super_admin',
        skill_level: '5.0',
        membership_status: 'elite',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Vallarta 1234, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'SUPA800115HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ admin_certificate: 'ADMIN123456' }),
        notes: 'System administrator with full access',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ admin_level: 'super', permissions: ['all'] }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Player
      {
        id: '550e8400-e29b-41d4-a716-446655440002',
        username: 'john_player',
        email: 'john@email.com',
        password_hash: hashedPassword,
        full_name: 'John Smith',
        date_of_birth: '1990-03-15',
        gender: 'male',
        phone: '+52-55-6789-0123',
        profile_photo: 'https://example.com/photos/john.jpg',
        bio: 'Intermediate player looking for regular matches',
        user_type: 'player',
        skill_level: '3.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Calle Libertad 123, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'SMIT900315HJCMNR01',
        rfc: null,
        website: null,
        verification_documents: JSON.stringify({ player_license: 'PLAYER123456' }),
        notes: 'Active player with good attendance',
        preferences: JSON.stringify({ notifications: true, language: 'en' }),
        metadata: JSON.stringify({ player_stats: { matches_played: 45, wins: 28 } }),
        club_id: '660e8400-e29b-41d4-a716-446655440001', // Elite Pickleball Club
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Club
      {
        id: '550e8400-e29b-41d4-a716-446655440003',
        username: 'elite_club',
        email: 'info@elitepickleball.com',
        password_hash: hashedPassword,
        full_name: 'Elite Pickleball Club',
        date_of_birth: null,
        gender: null,
        phone: '+52-55-4567-8901',
        profile_photo: 'https://example.com/photos/elite_club.jpg',
        bio: 'Premium pickleball club with multiple courts',
        user_type: 'club',
        skill_level: null,
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Chapultepec 456, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        business_name: 'Elite Pickleball Club',
        contact_person: 'Maria Rodriguez',
        job_title: 'Club Manager',
        curp: null,
        rfc: 'ELI123456789',
        website: 'https://www.elitepickleball.com',
        verification_documents: JSON.stringify({ business_license: 'LIC123456' }),
        notes: 'Premium club with excellent facilities',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ club_stats: { members: 150, courts: 6 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Coach
      {
        id: '550e8400-e29b-41d4-a716-446655440004',
        username: 'coach_sarah',
        email: 'sarah@pickleballcoach.com',
        password_hash: hashedPassword,
        full_name: 'Sarah Johnson',
        date_of_birth: '1985-07-22',
        gender: 'female',
        phone: '+52-55-9876-5432',
        profile_photo: 'https://example.com/photos/sarah.jpg',
        bio: 'Certified pickleball coach with 10+ years experience',
        user_type: 'coach',
        skill_level: '5.5',
        membership_status: 'premium',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Calle Morelos 789, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        business_name: null,
        contact_person: null,
        job_title: null,
        curp: 'JONS850722HJCMNR01',
        rfc: null,
        website: 'https://www.sarahpickleballcoach.com',
        verification_documents: JSON.stringify({ coaching_certificate: 'CERT123456' }),
        notes: 'Excellent coach for beginners and intermediate players',
        preferences: JSON.stringify({ notifications: true, language: 'en' }),
        metadata: JSON.stringify({ coach_stats: { students: 25, certifications: ['USAPA', 'IPTPA'] } }),
        club_id: '660e8400-e29b-41d4-a716-446655440001', // Elite Pickleball Club
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // Partner (Hotel)
      {
        id: '550e8400-e29b-41d4-a716-446655440005',
        username: 'hotel_resort',
        email: 'info@hotelresort.com',
        password_hash: hashedPassword,
        full_name: 'Hotel Resort & Pickleball Center',
        date_of_birth: null,
        gender: null,
        phone: '+52-55-1111-2222',
        profile_photo: 'https://example.com/photos/hotel.jpg',
        bio: 'Luxury hotel with dedicated pickleball courts',
        user_type: 'partner',
        skill_level: null,
        membership_status: 'basic',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Puerto Vallarta',
        address: 'Boulevard Francisco Medina Ascencio 999, Puerto Vallarta, Jalisco',
        latitude: 20.6597,
        longitude: -105.2333,
        timezone: 'America/Mexico_City',
        business_name: 'Hotel Resort & Pickleball Center',
        contact_person: 'Carlos Mendoza',
        job_title: 'Sports Director',
        curp: null,
        rfc: 'HOT987654321',
        website: 'https://www.hotelresort.com',
        verification_documents: JSON.stringify({ hotel_license: 'HOT123456' }),
        notes: 'Partner hotel with excellent facilities',
        preferences: JSON.stringify({ notifications: true, language: 'es' }),
        metadata: JSON.stringify({ partner_stats: { courts: 4, hotel_rating: 4.5 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // State Representative - Jalisco
      {
        id: '550e8400-e29b-41d4-a716-446655440006',
        username: 'jalisco_state',
        email: 'jalisco@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Jalisco State Pickleball Federation',
        date_of_birth: null,
        gender: null,
        phone: '+52-33-1234-5678',
        profile_photo: 'https://example.com/photos/jalisco.jpg',
        bio: 'Official state representative for Jalisco Pickleball Federation',
        user_type: 'state',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Jalisco',
        city: 'Guadalajara',
        address: 'Av. Juárez 1234, Guadalajara, Jalisco',
        latitude: 20.6597,
        longitude: -103.3496,
        timezone: 'America/Mexico_City',
        business_name: 'Jalisco State Pickleball Federation',
        contact_person: 'María González',
        job_title: 'State Director',
        curp: null,
        rfc: 'JAL987654321',
        website: 'https://www.jalisco-pickleball.mx',
        verification_documents: JSON.stringify({ state_license: 'JAL123456', federation_certificate: 'FED789012' }),
        notes: 'Official state representative with authority to organize state-level tournaments',
        preferences: JSON.stringify({ notifications: true, language: 'es', state_notifications: true }),
        metadata: JSON.stringify({ state_stats: { clubs: 15, players: 1200, tournaments_organized: 8 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      },

      // State Representative - Nuevo León
      {
        id: '550e8400-e29b-41d4-a716-446655440007',
        username: 'nuevoleon_state',
        email: 'nuevoleon@pickleballfederation.mx',
        password_hash: hashedPassword,
        full_name: 'Nuevo León State Pickleball Federation',
        date_of_birth: null,
        gender: null,
        phone: '+52-81-9876-5432',
        profile_photo: 'https://example.com/photos/nuevoleon.jpg',
        bio: 'Official state representative for Nuevo León Pickleball Federation',
        user_type: 'state',
        skill_level: null,
        membership_status: 'elite',
        membership_expires_at: new Date(2025, 11, 31),
        email_verified: true,
        email_verification_token: null,
        email_verification_expires_at: null,
        password_reset_token: null,
        password_reset_expires_at: null,
        is_active: true,
        is_verified: true,
        last_login: now,
        login_attempts: 0,
        locked_until: null,
        state: 'Nuevo León',
        city: 'Monterrey',
        address: 'Av. Constitución 567, Monterrey, Nuevo León',
        latitude: 25.6866,
        longitude: -100.3161,
        timezone: 'America/Mexico_City',
        business_name: 'Nuevo León State Pickleball Federation',
        contact_person: 'Roberto Martínez',
        job_title: 'State Director',
        curp: null,
        rfc: 'NLE987654321',
        website: 'https://www.nuevoleon-pickleball.mx',
        verification_documents: JSON.stringify({ state_license: 'NLE123456', federation_certificate: 'FED789013' }),
        notes: 'Official state representative with authority to organize state-level tournaments',
        preferences: JSON.stringify({ notifications: true, language: 'es', state_notifications: true }),
        metadata: JSON.stringify({ state_stats: { clubs: 12, players: 950, tournaments_organized: 6 } }),
        club_id: null,
        created_at: now,
        updated_at: now,
        deleted_at: null
      }
    ];

    await queryInterface.bulkInsert('users', users, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('users', null, {});
  }
}; 